name: Build userstyles

on:
  workflow_dispatch:
  schedule: 
    # Every Wednesday at 12PM PST
    - cron: "20 12 * * 3"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [22]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Install Chrome
      run: npx puppeteer browsers install chrome

    - name: Build artifacts
      run: pnpm run build
      
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "ci: build userstyles"
        default_author: github_actions
        push: true
